name: pytest
# Run all pytests in the test folder

on: [ push, pull_request ]

permissions:
  contents: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r tests/requirements.txt
      - name: Test with pytest
        run: |
          pytest --tb=short -s
      - name: Create action summary
        run: |
          cat tests/logging.md >> $GITHUB_STEP_SUMMARY
        if: always()
